export default {
	"pages": {
		"root": {
			"id": "root",
			"pageUrl": "root",
			"name": "root",
			"children": [
				"6461957b820441001fb09af5",
				"6474df74588b2d00195721ab",
				"647f0c8a8bd7e60018589221",
				"647f0c8f477c3a0019b29f9d",
				"6461957b820441001fb09af2"
			]
		},
		"6461957b820441001fb09af2": {
			"id": "6461957b820441001fb09af2",
			"name": "404",
			"pageUrl": "404"
		},
		"6461957b820441001fb09af5": {
			"id": "6461957b820441001fb09af5",
			"name": "AB Digital Marketing",
			"pageUrl": "index",
			"customCode": {
				"6486a11bf658b8cdaff32dd6": {
					"name": "GTM",
					"place": "endOfHead",
					"tag": "script",
					"data": {
						"content": "<!-- Google Tag Manager -->\n<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':\nnew Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],\nj=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=\n'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);\n})(window,document,'script','dataLayer','GTM-T44CF6S');</script>\n<!-- End Google Tag Manager -->"
					}
				},
				"6486a123762b294f5b7adb32": {
					"name": "GTM",
					"place": "endOfBody",
					"tag": "script",
					"data": {
						"content": "<!-- Google Tag Manager (noscript) -->\n<noscript><iframe src=\"https://www.googletagmanager.com/ns.html?id=GTM-T44CF6S\"\nheight=\"0\" width=\"0\" style=\"display:none;visibility:hidden\"></iframe></noscript>\n<!-- End Google Tag Manager (noscript) -->"
					}
				}
			}
		},
		"6474df74588b2d00195721ab": {
			"pageUrl": "socmed",
			"id": "6474df74588b2d00195721ab",
			"name": "Social Media",
			"customCode": {
				"6486a13acf0d18fd19947124": {
					"name": "GTM",
					"place": "endOfBody",
					"tag": "script",
					"data": {
						"content": "<!-- Google Tag Manager (noscript) -->\n<noscript><iframe src=\"https://www.googletagmanager.com/ns.html?id=GTM-T44CF6S\"\nheight=\"0\" width=\"0\" style=\"display:none;visibility:hidden\"></iframe></noscript>\n<!-- End Google Tag Manager (noscript) -->"
					}
				},
				"6486a14282cb6b98aecf35a8": {
					"name": "GTM",
					"place": "endOfHead",
					"tag": "script",
					"data": {
						"content": "<!-- Google Tag Manager -->\n<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':\nnew Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],\nj=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=\n'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);\n})(window,document,'script','dataLayer','GTM-T44CF6S');</script>\n<!-- End Google Tag Manager -->"
					}
				}
			}
		},
		"647f0c8a8bd7e60018589221": {
			"pageUrl": "socmed1",
			"id": "647f0c8a8bd7e60018589221",
			"name": "SEO",
			"customCode": {
				"6486a1568e4fe0925793e17f": {
					"name": "GTM",
					"place": "endOfHead",
					"tag": "script",
					"data": {
						"content": "<!-- Google Tag Manager -->\n<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':\nnew Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],\nj=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=\n'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);\n})(window,document,'script','dataLayer','GTM-T44CF6S');</script>\n<!-- End Google Tag Manager -->"
					}
				},
				"6486a15ea3d9b52bda9ca95a": {
					"name": "GTM",
					"place": "endOfBody",
					"tag": "script",
					"data": {
						"content": "<!-- Google Tag Manager (noscript) -->\n<noscript><iframe src=\"https://www.googletagmanager.com/ns.html?id=GTM-T44CF6S\"\nheight=\"0\" width=\"0\" style=\"display:none;visibility:hidden\"></iframe></noscript>\n<!-- End Google Tag Manager (noscript) -->"
					}
				}
			}
		},
		"647f0c8f477c3a0019b29f9d": {
			"pageUrl": "socmed11",
			"id": "647f0c8f477c3a0019b29f9d",
			"name": "CRM"
		}
	},
	"mode": "production",
	"projectType": "gatsby",
	"site": {
		"styles": {},
		"seo": {
			"title": "Digital Marketing Notion Template",
			"favicon_32px": "https://uploads.quarkly.io/6461957b820441001fb09aed/images/Logo_FB_Ads_Mastery__3_-removebg-preview.png?v=2023-05-16T17:17:02.308Z",
			"favicon_apple_152px": "https://uploads.quarkly.io/6461957b820441001fb09aed/images/Logo_FB_Ads_Mastery__3_-removebg-preview.png?v=2023-05-16T17:17:02.308Z",
			"favicon_win10_270px": "https://uploads.quarkly.io/6461957b820441001fb09aed/images/Logo_FB_Ads_Mastery__3_-removebg-preview.png?v=2023-05-16T17:17:02.308Z",
			"description": "AB Digital Marketing menyediakan berbagai template notion untuk digital marketing mulai dari social media, SEO, dan CRM.",
			"robotsFileType": "autogenerated",
			"sitemapFileType": "autogenerated"
		}
	}
}