export default {
	"pages": {
		"root": {
			"id": "root",
			"pageUrl": "root",
			"name": "root",
			"children": [
				"6461957b820441001fb09af5",
				"6474df74588b2d00195721ab",
				"647f0c8a8bd7e60018589221",
				"647f0c8f477c3a0019b29f9d",
				"6461957b820441001fb09af2"
			]
		},
		"6461957b820441001fb09af2": {
			"id": "6461957b820441001fb09af2",
			"name": "404",
			"pageUrl": "404"
		},
		"6461957b820441001fb09af5": {
			"id": "6461957b820441001fb09af5",
			"name": "AB Digital Marketing",
			"pageUrl": "index",
			"customCode": {},
			"seo": {
				"title": "",
				"description": "",
				"og:title": ""
			}
		},
		"6474df74588b2d00195721ab": {
			"pageUrl": "socmed",
			"id": "6474df74588b2d00195721ab",
			"name": "Social Media",
			"customCode": {
				"64933641ff7c78f8c3f7c8c5": {
					"name": "GTM",
					"place": "endOfHead",
					"tag": "script",
					"data": {
						"content": "<!-- Google Tag Manager -->\n<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':\nnew Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],\nj=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=\n'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);\n})(window,document,'script','dataLayer','GTM-KS2DQJB');</script>\n<!-- End Google Tag Manager -->"
					}
				},
				"6493364d8b49c5b221f87a01": {
					"name": "GTM",
					"place": "endOfBody",
					"tag": "script",
					"data": {
						"content": "<!-- Google Tag Manager (noscript) -->\n<noscript><iframe src=\"https://www.googletagmanager.com/ns.html?id=GTM-KS2DQJB\"\nheight=\"0\" width=\"0\" style=\"display:none;visibility:hidden\"></iframe></noscript>\n<!-- End Google Tag Manager (noscript) -->"
					}
				}
			},
			"seo": {
				"description": "AB Digital Marketing menyediakan berbagai template notion untuk digital marketing mulai dari social media, SEO, dan CRM.",
				"title": "Social Media Notion Template"
			}
		},
		"647f0c8a8bd7e60018589221": {
			"pageUrl": "seo",
			"id": "647f0c8a8bd7e60018589221",
			"name": "SEO",
			"customCode": {},
			"seo": {
				"title": "SEO Notion Template",
				"description": "AB Digital Marketing menyediakan berbagai template notion untuk digital marketing mulai dari social media, SEO, dan CRM."
			}
		},
		"647f0c8f477c3a0019b29f9d": {
			"pageUrl": "socmed11",
			"id": "647f0c8f477c3a0019b29f9d",
			"name": "CRM"
		}
	},
	"mode": "production",
	"projectType": "gatsby",
	"site": {
		"styles": {},
		"seo": {
			"title": "",
			"favicon_32px": "https://uploads.quarkly.io/6461957b820441001fb09aed/images/Logo_FB_Ads_Mastery__3_-removebg-preview.png?v=2023-05-16T17:17:02.308Z",
			"favicon_apple_152px": "https://uploads.quarkly.io/6461957b820441001fb09aed/images/Logo_FB_Ads_Mastery__3_-removebg-preview.png?v=2023-05-16T17:17:02.308Z",
			"favicon_win10_270px": "https://uploads.quarkly.io/6461957b820441001fb09aed/images/Logo_FB_Ads_Mastery__3_-removebg-preview.png?v=2023-05-16T17:17:02.308Z",
			"description": "",
			"robotsFileType": "autogenerated",
			"sitemapFileType": "autogenerated",
			"customSitemapDomain": "https://abdigitalmarketing.xyz"
		}
	}
}