export default {
	"pages": {
		"root": {
			"id": "root",
			"pageUrl": "root",
			"name": "root",
			"children": [
				"6461957b820441001fb09af2",
				"6461957b820441001fb09af5",
				"6474df74588b2d00195721ab"
			]
		},
		"6461957b820441001fb09af2": {
			"id": "6461957b820441001fb09af2",
			"name": "404",
			"pageUrl": "404"
		},
		"6461957b820441001fb09af5": {
			"id": "6461957b820441001fb09af5",
			"name": "AB Digital Marketing",
			"pageUrl": "index"
		},
		"6474df74588b2d00195721ab": {
			"pageUrl": "socmed",
			"id": "6474df74588b2d00195721ab",
			"name": "Social Media"
		}
	},
	"mode": "production",
	"projectType": "gatsby",
	"site": {
		"styles": {},
		"seo": {
			"title": "AB Digital Marketing",
			"favicon_32px": "https://uploads.quarkly.io/6461957b820441001fb09aed/images/Logo_FB_Ads_Mastery__3_-removebg-preview.png?v=2023-05-16T17:17:02.308Z",
			"favicon_apple_152px": "https://uploads.quarkly.io/6461957b820441001fb09aed/images/Logo_FB_Ads_Mastery__3_-removebg-preview.png?v=2023-05-16T17:17:02.308Z",
			"favicon_win10_270px": "https://uploads.quarkly.io/6461957b820441001fb09aed/images/Logo_FB_Ads_Mastery__3_-removebg-preview.png?v=2023-05-16T17:17:02.308Z",
			"description": "Social Media Planner Template",
			"robotsFileType": "autogenerated",
			"sitemapFileType": "autogenerated"
		}
	}
}